# Generated by Django 6.0.5 on 2026-05-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_managers_remove_user_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="mobile_number",
            field=models.CharField(
                blank=True, help_text="For WhatsApp/Contact matching", max_length=15
            ),
        ),
    ]
